language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
script:
 - nosetests systemsgo/tests/
after_success:
 - coverage run --source=. systemsgo/tests/tests_unit/test_webservices.py
 - coveralls
